version: '3.8'
services:
  auth:
    build: ./services/auth
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  faas:
    build: ./services/faas
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - nats
      - auth
    networks:
      - app-network 

  orquestador:
    build: ./services/orquestador
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - nats
    networks:
      - app-network

  worker:
    build: ./services/worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nats
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge